//! The application icon — the one Phoebus carries inside the binary.
//!
//! There are three places an icon can come from and Phoebus uses all three:
//!
//! | where | what supplies it |
//! |-------|------------------|
//! | Linux taskbars / window managers | [`window_icon`] via `ViewportBuilder::with_icon` |
//! | macOS Dock and ⌘-Tab, run unbundled | [`set_dock_icon`] via AppKit |
//! | macOS 26 Dock, run from `Phoebus.app` | `Contents/Resources/Assets.car` in the bundle |
//! | macOS 11…15 Dock, run from `Phoebus.app` | `Contents/Resources/Phoebus.icns` |
//!
//! The embedded PNG is `assets/icon/phoebus-256.png`, rendered from
//! `assets/icon/phoebus.svg` by `scripts/make-icons.sh`. It is the *plate* artwork (the
//! Big Sur rounded square with a transparent margin), not the full-bleed square: nothing
//! masks a macOS Dock icon, so a square would sit in the Dock as a hard-edged tile. Linux
//! window managers are happy with the transparent margin, and the launcher entry there
//! resolves `Icon=phoebus` against the full-bleed hicolor set instead
//! (`assets/icon/hicolor/`, see `assets/README.md`).
//!
//! It lives in the repo-wide `assets/icon/` rather than `crates/phoebus-app/assets/`
//! because the same file is the input to the `.icns`, the hicolor set and the `.app`
//! bundle; keeping one copy is what makes `scripts/make-icons.sh` the single source of
//! truth. `crates/phoebus-app/assets/` stays what its README says it is — third-party
//! fonts with licences attached.
//!
//! **Nothing here is allowed to fail loudly.** An icon is decoration; a music player that
//! refuses to open a window because a PNG did not decode is a bug. Every path returns or
//! logs at `warn` and carries on.

/// The 256 × 256 plate, generated by `scripts/make-icons.sh` and checked in so that
/// building from source needs neither `rsvg-convert` nor a Mac.
const PNG: &[u8] = include_bytes!("../../../assets/icon/phoebus-256.png");

/// Decode the embedded PNG into the straight-RGBA buffer egui's `IconData` wants.
///
/// `None` means "leave the platform default alone" — `ViewportBuilder::with_icon` takes an
/// `IconData` by value, so the caller has to decide *not to call it* rather than pass
/// something empty.
pub fn window_icon() -> Option<egui::IconData> {
    match image::load_from_memory_with_format(PNG, image::ImageFormat::Png) {
        Ok(image) => {
            let rgba = image.into_rgba8();
            let (width, height) = rgba.dimensions();
            Some(egui::IconData {
                rgba: rgba.into_raw(),
                width,
                height,
            })
        }
        Err(e) => {
            log::warn!("window icon: could not decode the embedded PNG: {e}");
            None
        }
    }
}

/// Give the macOS Dock (and ⌘-Tab) the real icon when Phoebus runs **unbundled**.
///
/// `cargo run` and `./target/release/phoebus` produce a process with no `Info.plist`, so
/// AppKit has no `CFBundleIconFile` to read and falls back to the generic executable
/// rocket. `-[NSApplication setApplicationIconImage:]` is the documented override.
///
/// It is also a *replacement*, which is why a bundled run returns early. The setter swaps
/// the process's icon wholesale: called from `Phoebus.app` it would throw away whatever
/// LaunchServices resolved from the `Info.plist` — the `Assets.car` icon on macOS 26, the
/// ten-representation `Phoebus.icns` before that — and leave this single 256 px raster in
/// its place, which a Retina Dock (and ⌘-Tab, which asks for far more than 256) then has
/// to scale up. A bundle already has the better icon; the runtime override exists only for
/// the processes that have none.
///
/// Must run on the main thread — hence the [`MainThreadMarker`](objc2::MainThreadMarker),
/// which is `None` anywhere else and turns the whole thing into a no-op rather than a
/// crash. eframe's app-creation closure runs on the main thread, which is where the caller
/// puts this.
#[cfg(target_os = "macos")]
pub fn set_dock_icon() {
    use objc2::{AllocAnyThread, MainThreadMarker};
    use objc2_app_kit::{NSApplication, NSImage};
    use objc2_foundation::NSData;

    if running_from_bundle() {
        log::debug!("dock icon: bundled, leaving Contents/Resources/Phoebus.icns in place");
        return;
    }
    let Some(mtm) = MainThreadMarker::new() else {
        log::warn!("dock icon: not on the main thread, leaving the default");
        return;
    };
    let data = NSData::with_bytes(PNG);
    let Some(image) = NSImage::initWithData(NSImage::alloc(), &data) else {
        log::warn!("dock icon: AppKit could not decode the embedded PNG");
        return;
    };
    let app = NSApplication::sharedApplication(mtm);
    // The one place `unsafe` is allowed in this crate (see the crate-level `deny`): AppKit
    // setters are `unsafe fn` in objc2 across the board, because objc2 cannot prove the
    // receiver is the class it claims to be. Here it is, straight from
    // `NSApplication::sharedApplication`.
    //
    // SAFETY: `app` is the process's `NSApplication` and `image` a live `NSImage`; the
    // selector takes a nullable `NSImage*` and we are on the main thread. AppKit retains
    // the image, so dropping our `Retained` at the end of the scope is fine.
    #[allow(unsafe_code)]
    unsafe {
        app.setApplicationIconImage(Some(&image))
    };
    // The setter returns nothing and the Dock is not something a test can read back, so
    // this line is the only evidence a run leaves behind that the icon actually landed:
    // `RUST_LOG=phoebus=debug` prints it, `info` (the default) does not.
    log::debug!("dock icon: {} bytes of PNG handed to AppKit", PNG.len());
}

/// Was this process launched out of a `.app`?
///
/// The question `NSBundle.mainBundle.bundleIdentifier != nil` answers, asked of the
/// executable's path instead: same answer for every way Phoebus is actually started, but a
/// pure function that needs no extra AppKit surface — and so no second `unsafe` — to ask.
/// A `current_exe()` that fails at all is treated as unbundled, which is the safe way
/// round: the worst case is the icon we already ship being set twice.
#[cfg(target_os = "macos")]
fn running_from_bundle() -> bool {
    std::env::current_exe().is_ok_and(|exe| in_bundle_layout(&exe))
}

/// `…/Something.app/Contents/MacOS/<exe>` — the layout `scripts/bundle-macos.sh` writes and
/// the only one LaunchServices reads an `Info.plist` out of. Anything else (`target/debug`,
/// `target/release`, a bare copy on `$PATH`) is an unbundled run.
#[cfg(target_os = "macos")]
fn in_bundle_layout(exe: &std::path::Path) -> bool {
    let mut up = exe.ancestors().skip(1);
    up.next()
        .is_some_and(|dir| dir.file_name() == Some("MacOS".as_ref()))
        && up
            .next()
            .is_some_and(|dir| dir.file_name() == Some("Contents".as_ref()))
        && up
            .next()
            .is_some_and(|dir| dir.extension() == Some("app".as_ref()))
}

/// Everywhere else the window icon is the whole story.
#[cfg(not(target_os = "macos"))]
pub fn set_dock_icon() {}

#[cfg(test)]
mod tests {
    use super::*;

    /// The generated PNG is checked in, so this also catches "somebody edited the SVG and
    /// forgot to re-run `scripts/make-icons.sh`" turning the file into something egui
    /// cannot use.
    #[test]
    fn the_embedded_icon_decodes_to_a_square_rgba_buffer() {
        let icon = window_icon().expect("the embedded PNG must decode");
        assert_eq!((icon.width, icon.height), (256, 256));
        assert_eq!(icon.rgba.len(), 256 * 256 * 4);
        // The Big Sur plate leaves a transparent margin; the centre is opaque navy.
        let px = |x: usize, y: usize| {
            let i = (y * 256 + x) * 4;
            [
                icon.rgba[i],
                icon.rgba[i + 1],
                icon.rgba[i + 2],
                icon.rgba[i + 3],
            ]
        };
        assert_eq!(px(0, 0)[3], 0, "the plate must not reach the canvas corner");
        assert_eq!(px(128, 128)[3], 255, "the centre must be opaque");
    }

    /// The guard that keeps `set_dock_icon` from overwriting the bundle's ten-representation
    /// `Phoebus.icns` with one 256 px raster. Driven off paths because that is the half of
    /// the decision a test can hold still — `current_exe()` inside a test binary is neither
    /// of the two cases that matter.
    #[cfg(target_os = "macos")]
    #[test]
    fn only_a_dot_app_layout_counts_as_bundled() {
        use std::path::Path;
        let bundled = Path::new("/Applications/Phoebus.app/Contents/MacOS/phoebus");
        assert!(in_bundle_layout(bundled), "the installed bundle");
        assert!(
            in_bundle_layout(Path::new(
                "/Users/x/phoebus/target/bundle/Phoebus.app/Contents/MacOS/phoebus"
            )),
            "the same layout straight out of scripts/bundle-macos.sh"
        );
        for unbundled in [
            "/Users/x/phoebus/target/debug/phoebus", // cargo run
            "/Users/x/phoebus/target/release/phoebus",
            "/usr/local/bin/phoebus", // a bare copy on $PATH
            "/Applications/Phoebus.app/Contents/Resources/phoebus", // not the MacOS dir
            "/Applications/Phoebus/Contents/MacOS/phoebus", // no `.app` extension
            "phoebus",
        ] {
            assert!(
                !in_bundle_layout(Path::new(unbundled)),
                "{unbundled} must still get the runtime override"
            );
        }
    }
}
